[package]
name = "resolver"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ast = { version = "0.2.0-rc.1", path = "../ast" }
diagnostics = { path = "../diagnostics" }
module = { version = "0.2.0-rc.1", path = "../module" }
package = { version = "0.2.0-rc.1", path = "../package" }
