[package]
name = "cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ast = { version = "0.1.0", path = "../ast" }
clap = { version = "4.6.6", features = ["derive"] }
codegen = { version = "0.1.0", path = "../codegen" }
lexer = { version = "0.1.0", path = "../lexer" }
linker = { version = "0.1.0", path = "../linker" }
lowering = { version = "0.1.0", path = "../lowering" }
mir = { version = "0.1.0", path = "../mir" }
parser = { version = "0.1.0", path = "../parser" }
resolver = { version = "0.1.0", path = "../resolver" }
typechecker = { version = "0.1.0", path = "../typechecker" }
vm = { version = "0.1.0", path = "../vm" }
arc = { version = "0.1.0", path = "../arc" }
diagnostics = { path = "../diagnostics" }
toml = "1.1.4"
serde = { version = "1.0.229", features = ["derive"] }
package = { version = "0.1.0", path = "../package" }
module = { version = "0.1.0", path = "../module" }

[dev-dependencies]
insta = { version = "1.41.0", features = ["redactions"] }
