[workspace]
members = ["crates/pace-ast","crates/pace-cli", "crates/pace-codegen", "crates/pace-driver", "crates/pace-errors", "crates/pace-parser", "crates/pace-ty"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Pace Contributors"]
rust-version = "1.98.0"
license = "MIT"

[workspace.dependencies]
bumpalo = "3.20.3"
clap = { version = "4.6.6", features = ["derive"] }
chumsky = "0.13.0"
ariadne = "0.6.0"
miette = { version = "7.6.0", features = ["fancy"] }
insta = { version = "1.48", features = ["yaml"] }

# Local workspace crates
pace-ast = { path = "crates/pace-ast" }
pace-parser = { path = "crates/pace-parser" }
pace-errors = { path = "crates/pace-errors" }
pace-driver = { path = "crates/pace-driver" }
pace-ty = { path = "crates/pace-ty" }
pace-codegen = { path = "crates/pace-codegen" }

cranelift = "0.106.0"
cranelift-module = "0.106.0"
cranelift-jit = "0.106.0"
cranelift-native = "0.106.0"
