[package]
name = "pace-codegen"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pace-ast = { workspace = true }
pace-errors = { workspace = true }
cranelift = "0.135.0"
cranelift-module = "0.135.0"
cranelift-jit = "0.135.0"
cranelift-native = "0.135.0"
cranelift-object = "0.135.0"
object = { workspace = true }
miette = { workspace = true }
thiserror = "2.0.20"
pace-runtime = { version = "0.1.0", path = "../pace-runtime" }
