[package]
name = "pace-codegen-cranelift"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pace-ast = { workspace = true }
pace-errors = { workspace = true }
cranelift = { workspace = true }
    cranelift-module = { workspace = true }
cranelift-native = { workspace = true }
cranelift-object = { workspace = true }
object = { workspace = true }
miette = { workspace = true }
thiserror = "2"
pace-runtime = { version = "0.1.0", path = "../pace-runtime" }
ustr = "1.1.0"
pace-mir = { version = "0.1.0", path = "../pace-mir" }
pace-ty = { version = "0.1.0", path = "../pace-ty" }

[lints]
workspace = true
