[package]
name = "pace-parser"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
pace-errors = { workspace = true }
pace-ast = { workspace = true }
ustr = "1.1.0"
pace-span = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
