[package]
name = "typechecker"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ast = { path = "../ast" }
diagnostics = { path = "../diagnostics" }
generics = { path = "../generics" }
module = { version = "0.2.0", path = "../module" }
