[package]
name = "typechecker"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ast = { path = "../ast" }
bumpalo = "3.14.0"
diagnostics = { path = "../diagnostics" }
generics = { path = "../generics" }
module = { version = "0.1.0", path = "../module" }
session = { path = "../session" }
