[package]
name = "pace-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pace-lsp = { path = "../pace-lsp" }
clap = { workspace = true }
miette = { workspace = true }
pace-driver = { workspace = true }
pace-pkg = { workspace = true }
serde = { workspace = true }
ureq = { workspace = true }
walkdir = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
serde_json = "1.0"
dialoguer = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
cranelift.workspace = true
cranelift-codegen = "0.135.1"

[[bin]]
name = "pace"
path = "src/main.rs"
