[package]
name = "pace-errors"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
pace-common = { version = "0.1.0", path = "../pace-common" }
thiserror = "2"

[lints]
workspace = true
