[package]
name = "pace-ty"
version = "0.1.0"
edition = "2024"

[dependencies]
pace-hir = { path = "../pace-hir" }
pace-ast = { path = "../pace-ast" }
pace-span = { path = "../pace-span" }
pace-errors = { path = "../pace-errors" }

[dev-dependencies]
pace-lexer = { path = "../pace-lexer" }
pace-parser = { path = "../pace-parser" }
