[package]
name = "pace-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pace"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
pace-pkg = { path = "../pace-pkg" }
pace-driver = { path = "../pace-driver" }
pace-lsp = { path = "../pace-lsp" }
tokio = { version = "1.0", features = ["full"] }
semver = "1.0.28"
mimalloc = "0.1.43"
