[package]
name = "runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
libc = "0.2.189"
ureq = { version = "2.9", features = ["tls"] }
tiny_http = "0.12"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync"] }

[lib]
name = "pace_runtime"
crate-type = ["staticlib"]
