[package]
name = "pace-lsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tower-lsp = "0.20.0"
tokio = { version = "1.35", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1.10.0"
miette.workspace = true

pace-driver = { path = "../pace-driver" }
pace-errors = { path = "../pace-errors" }
pace-ast = { path = "../pace-ast" }
pace-ty = { path = "../pace-ty" }
pace-session = { path = "../pace-session" }
walkdir.workspace = true
pathdiff = "0.2.3"
ustr = "1.1.0"
pace-hir = { version = "0.1.0", path = "../pace-hir" }

[lints]
workspace = true
